# Generated by Django 3.2.4 on 2021-06-29 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_log', '0004_rename_name_exercise_ex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='ex',
            new_name='name',
        ),
    ]
